language: python
python:
- '3.7'
jobs:
  include:
  - stage: test and lint
    name: python test
    python: '3.7'
    install:
    - pip install pipenv
    - pipenv install -d
    script:
    - pipenv run flake8 .
    - pytest
  - name: js test
    node_js: '12'
    install:
    - npm install -D
    script:
    - npm run test
  - stage: deploy
    python: 3.7
    script: echo "Deploying to gae ..."
    install:
    - pip install pipenv
    before_deploy:
    - pipenv lock -r > requirements.txt
    deploy:
      provider: gae
      skip_cleanup: true
      keyfile: client-secret.json
      project: loveat2
      on:
        branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_caace5a6e9e3_key -iv $encrypted_caace5a6e9e3_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
